# Generated by Django 4.1.7 on 2023-03-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup_db',
            old_name='current_time',
            new_name='current_date_time',
        ),
    ]
