# Generated by Django 4.1.7 on 2023-03-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_audio_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio_db1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, null=True)),
                ('audio_file', models.FileField(upload_to='./Audio_media')),
                ('current_date_time', models.DateTimeField(auto_now=True)),
                ('signup_db_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.signup_db')),
            ],
        ),
        migrations.DeleteModel(
            name='audio_db',
        ),
    ]
