# Generated by Django 4.1.7 on 2023-03-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_audio_db1_delete_audio_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio_db1',
            old_name='fname',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='audio_db1',
            name='audio_file',
            field=models.FileField(upload_to='Audio_media/'),
        ),
    ]
