# Generated by Django 4.1.7 on 2023-03-03 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_fname_audio_db1_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio_db1',
            name='signup_db_user',
        ),
    ]
